### GET request to retrieve all items
GET http://localhost:8080/

### POST request to create a new item
POST http://localhost:8081/predict
Content-Type: application/json

{
  "type": [1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0]
}